#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const htmlPath = path.join(__dirname, 'index.html');
const html = fs.readFileSync(htmlPath, 'utf8');
let failed = false;
function ok(label, condition, detail='') {
  if (condition) console.log(`PASS  ${label}`);
  else { console.error(`FAIL  ${label}${detail ? ` — ${detail}` : ''}`); failed = true; }
}

// Extract classic inline scripts and syntax-check each one.
const scripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
const tmp = path.join(__dirname, '.syntax-check.js');
for (let i=0;i<scripts.length;i++) {
  fs.writeFileSync(tmp, scripts[i]);
  try { execFileSync(process.execPath, ['--check', tmp], {stdio:'pipe'}); ok(`inline script ${i+1} syntax` , true); }
  catch (e) { ok(`inline script ${i+1} syntax`, false, e.stderr?.toString().trim().split('\n').slice(-2).join(' ')); }
}
try { fs.unlinkSync(tmp); } catch {}

// Actual HTML DOM IDs (not strings generated by JS).
const markupOnly = html.replace(/<script(?:\s[^>]*)?>[\s\S]*?<\/script>/gi, '');
const ids = [];
for (const m of markupOnly.matchAll(/\bid=["']([^"']+)["']/g)) ids.push(m[1]);
const dupIds = [...new Set(ids.filter((id,i)=>ids.indexOf(id)!==i))];
ok('static DOM ids are unique', dupIds.length===0, dupIds.join(', '));

// Global function names in source must be unique; boot layers use explicit names.
const fnNames = [];
for (const m of html.matchAll(/(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/g)) fnNames.push(m[1]);
const dupFns = [...new Set(fnNames.filter((n,i)=>fnNames.indexOf(n)!==i))];
ok('global function definitions are unique', dupFns.length===0, dupFns.join(', '));
ok('single boot orchestrator exists', /id=["']rafiq-v100-boot["']/.test(html));
ok('core boot is named', /function initCore\s*\(/.test(html));
ok('Zad learning boot is named', /function initZadLearningLayer\s*\(/.test(html));
ok('release library boot is named', /function initReleaseLibrary\s*\(/.test(html));
ok('schema migration exists', /function migrateState\s*\(/.test(html));
ok('service worker uses v100', /sw\.js\?v=100/.test(html));

const sw = fs.readFileSync(path.join(__dirname,'sw.js'),'utf8');
ok('service worker cache is v100', /rafiq-shell-v100/.test(sw));
ok('service worker has offline navigation fallback', /req\.mode === 'navigate'[\s\S]*caches\.match\('\.\/index\.html'\)/.test(sw));

// Required project assets are allowed to be absent from this compact source bundle,
// but the README must explicitly document that dependency rather than silently failing.
const readme = fs.readFileSync(path.join(__dirname,'README.txt'),'utf8');
ok('bundle README documents external required assets', /quran-uthmani\.json|manifest\.webmanifest/.test(readme));

if (failed) process.exit(1);
console.log('\nAll V100 static checks passed.');
